name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
      - name: Run CI checks
        run: deno task ci
      - name: Publish package
        run: npx jsr publish
